### ISSUE TITLE
Feature request of real 3D (XYZ) support instead of XZ

### ISSUE THREAD

**Issue by 353055619** [Nebukam/com.nebukam.orca#1]
Your solution to 3D scenes is to convert XY into XZ. I couldn't make out _the difference between XY and XZ_, which are both 2D planes.

Real 3D (**XYZ**) support is intended to be suitable for many novel applications, such as unmanned aerial vehicles (UAVs) light shows.

I do not excel in ORCA. This is just a thought. I appreciate your excellent work. Thank you!

**Comment by Nebukam** [comment]
Hey there! Thanks a lot for the kind comment!
It is indeed more of a 2.5D than actual 3D -- what I meant by 3D is that it does support planar calculations + differences in elevation (based on which plane is selected), in order to better accommodate whatever axis your project is set-up for in Unity : if you chose `XY`, `Z` is used, where `XZ` considers `Y` to rule out collisions & detection. In addition agents & obstacles have an `height` property... It's indeed not as usefull as true 3D :(

2D Projects usually work on XY, while 3D projects are on XZ.

You can look at [RVO2-3D](https://github.com/snape/RVO2-3D) which might be what you're looking for?
As far as the com.nebukam.orca package goes, i'm using it primarily for gamedev which usually can't afford the heaviness that comes with linear program in 3D so I doubt I'll ever find the time to make an update.  
I'll evaluate the library linked above at some point in the future and see how complex that would be to offer real 3D with the current library, but no promises u_u
