### ISSUE TITLE
Error building Player because scripts had compiler errors

### ISSUE THREAD

**Issue by 353055619** [Nebukam/com.nebukam.orca#2]
**Describe the bug**
There are always compiler errors when building a scence. I am not expecting your extra work to fix the bug, because I actually have a slightly more complicated alternate plan for building the scence. Please let me know if you have any ideas on how to fix the following bug. Please accept my thanks for the trouble you have taken.

<img width="1125" alt="image" src="https://user-images.githubusercontent.com/35963306/166129945-c61d1ff9-c138-46d8-a34e-ac28ac3cd859.png">

**Device info**
- Macbook pro
  - Processor: Apple M1 Pro
  - OS: macOS Monterey 12.3.1

**Unity info**
- Version: 2021.2.16f1c1

**Comment by Nebukam** [comment]
Hey @353055619 ! It's actually a super easy fix, it's a typo on my end; the fix is actually super easy I just never took the time to try and build a project with this lib.  

I'm going to push an update the the package in a few that should fix the issue.  
Meanwhile, if you want to fix it on your end :

- locate the package com.nebukam.job-assist (should be in your project Package folder)
- at line 409, here are the changes : 
![image](https://user-images.githubusercontent.com/5935407/166131440-6e5aecac-47f8-4470-ad08-2497babbbcff.png)

In other words, replace

``` CSharp
    if (m_disposed)
    {
        return;
#if UNITY_EDITOR
        //throw new Exception("DisposeAll() called on already disposed Compound.");
#endif
    }
```

by


``` CSharp
#if UNITY_EDITOR
            if (m_disposed)
            {
                return;

                //throw new Exception("DisposeAll() called on already disposed Compound.");
            }
#endif
```

`m_disposed` only exists at editor time, hence the build fails :(

Will close the issue once the package is updated (meaning you will need to uninstall/reinstall the packages and its dependencies)

**Comment by Nebukam** [comment]
@353055619 issue should be solved. Thanks a lot for the report 🙏
