### ISSUE TITLE
Error depencie on unity 2021.3.17f1

### ISSUE THREAD

**Issue by victormartinezsimon** [Nebukam/com.nebukam.orca#3]
I create a clean proyect to test this package and I have this error:

`Library\PackageCache\com.unity.jobs@0.2.10-preview.13\Unity.Jobs\IJobParallelForDefer.cs(73,85): error CS8377: The type 'U' must be a non-nullable value type, along with all fields at any level of nesting, in order to use it as parameter 'T' in the generic type or method 'NativeList<T>'`

I think there are some bad depencies that shouldn't be used. 

Thank you

**Comment by Nebukam** [comment]
Thanks for the report!

I'll be looking into this ASAP -- never seen that issue before.
It's a bit odd since `com.unity.jobs@0.2.10-preview.13` has always been functional, and shouldn't have been updated by anyone.

A quick research yield this : https://forum.unity.com/threads/cant-see-jobs-package-in-2021.1182445/, not sure it's related but this could possibly means there is a collision between Job Assist (ORCA depends on it) imports and existing libraries in 2021.3.17f1; and [these are Job Assist' dependencies](https://github.com/Nebukam/com.nebukam.job-assist/blob/master/package.json).

When you say "clean project" -- can you give me a quick step-by-step of everything you do so I can try to reproduce the issue at home?

Thank you so much!

**Comment by Nebukam** [comment]
Looks like the Jobs API is available without packages as of 2021.3
https://docs.unity3d.com/Manual/JobSystemParallelForJobs.html

I'll have to add some compiler branching in the dependencies to support it -- not a huge task but not sure when I'll have the bandwidth for that and don't want to commit to something.
I'd recommend doing a quick test with a previous version of Unity to see if the package would fit your need in the short term?

**Comment by Nebukam** [comment]
Actually compiler branching won't cut it, the package will still be pulled and throw an error on 2021.3; I'll have to create an completely different repo just to have an alternative package.json :(

**Comment by victormartinezsimon** [comment]
Thanks for your fast answer.
By clean proyect I mean just create a proyect and do the installation process.
But it's there no solution without creating a new repo? :(

**Comment by Nebukam** [comment]
I'm looking into it right now :D
I'm currently updating com.unity.jobs `0.13` ->` 0.51` and com.unity.collections `0.0.9` -> `1.3.1`  (long due update), making sure it still works in the minimum version I'm supporting (2020.3.11f1); and then see if that fixes the issue in 2022.3!

**Comment by Nebukam** [comment]
Hey @victormartinezsimon! Good news!
I was not able to download the `2021.3.17f1` but I tested the updated package and it works on `2020.3.11f1` & `2022.1.0f1` so you should be good ^_^

If you:
- Start a project from scratch
- Open the Package Manager
- Add from git URL the Dependency Resolver `https://github.com/mob-sakai/GitDependencyResolverForUnity.git`
- Add ORCA from git URL `https://github.com/Nebukam/com.nebukam.orca.git`
(go over these [troubleshooting steps](https://github.com/Nebukam/com.nebukam.orca#installation-troubleshooting) if you encounter any issue)
- Import any example (the first one, Flock, should work)
- Click play and look at the editor view (not the play view)
- Confirm the issue is fixed on your end and that the code runs without issues

Let me know if this fixes the issue on your specific version :)

**Comment by victormartinezsimon** [comment]
Tested on `2021.3.17f1 ` and everything is working now.
Thank you
